# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2f08e1ea06bf0ef0e3af13c0c0dee0657ffa407721fcf92c685b426eb804bb4c86a4ac144436dc75af2a53268402d8778e8524c42db9251d0b8d5ed984fcf7cd

test:
  secret_key_base: 16f2d18351d70d36c84577d6687dcf68e6f95fda45f9698a0c6069879a7f06139c24b341d8c0f3c371f2bda3e21398b29b4a52e3b4fb28a4b7353dadf6a5bcde

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
